### ISSUE TITLE
空白の一貫性について

### ISSUE THREAD

**Issue by sakakazu2468** [forli1115/ProjExD#16]
https://github.com/forli1115/ProjExD/blob/d63b2396154bd88c5233a319f6287d712be7efb8/ex03/maze.py#L45
32, 45, 51, 54, 58, 59行目において、空白が統一されていないのでコードが読みにくくなってしまっています。特に45行目は危ないかもしれません。

**Comment by forli1115** [comment]
空白の数を統一させていただきました。
ご指摘ありがとうございました。
