### ISSUE TITLE
コメントアウト

### ISSUE THREAD

**Issue by yasuseri** [forli1115/ProjExD#17]
https://github.com/forli1115/ProjExD/blob/9bcfc1e53b5b24b84e704182e4c7b4ec9a9b7784/ex04/dodge_bomb.py#L1
全体的にコメントアウトが少なめなので重要な部分には追加した方がよいと思った

**Comment by forli1115** [comment]
全体のコメントアウトの量を増やしました。
ご指摘ありがとうございます。
